spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
  hibernate:
    ddl-auto: update
  h2:
    console.enabled: true
server:
  error:
    include-stacktrace: ON_PARAM
